### ISSUE TITLE
imageisux压缩对图片大小和尺寸有限制么？

### ISSUE THREAD

**Issue by lzhwWeb** [targetkiller/gulp-imageisux#6]
使用gulp-imageisux压缩图片发现图片尺寸或者size较大时提示
[15:52:04] [error] lottery_back22.png cannot post to the server.
该图片分辨率1242*3058，大小218K

**Comment by targetkiller** [comment]
@lzhwWeb 一般大于8m才会有问题，可能是没有更新最新的版本（更换了服务器）
